version: '3'
services:
  web:
    build:
      context: ./Docker
    links:
      - 'db:mysql'
    depends_on:
      - db
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - './Script:/var/www/html'
      - './Documentation:/var/www/html/docs'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
  db:
    image: 'mysql:8.0.22'
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: tvposts
      MYSQL_USER: tvposts
      MYSQL_PASSWORD: tvposts
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - './mysql:/var/lib/mysql'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M


